/* 
 * sms-client
 *
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Nvt.Celman.Api;
using Com.Nvt.Celman.Model;
using Com.Nvt.Celman.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Nvt.Celman.Test
{
    /// <summary>
    ///  Class for testing SmsSendRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SmsSendRequestTests
    {
        // TODO uncomment below to declare an instance variable for SmsSendRequest
        //private SmsSendRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmsSendRequest
            //instance = new SmsSendRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmsSendRequest
        /// </summary>
        [Test]
        public void SmsSendRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SmsSendRequest
            //Assert.IsInstanceOf(typeof(SmsSendRequest), instance);
        }


        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Test]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
