/* 
 * sms-client
 *
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Nvt.Celman.Api;
using Com.Nvt.Celman.Model;
using Com.Nvt.Celman.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Nvt.Celman.Test
{
    /// <summary>
    ///  Class for testing SmsSendResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SmsSendResponseTests
    {
        // TODO uncomment below to declare an instance variable for SmsSendResponse
        //private SmsSendResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmsSendResponse
            //instance = new SmsSendResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmsSendResponse
        /// </summary>
        [Test]
        public void SmsSendResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SmsSendResponse
            //Assert.IsInstanceOf(typeof(SmsSendResponse), instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
