/* 
 * sms-client
 *
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Com.Nvt.Celman.Client;
using Com.Nvt.Celman.Model;

namespace Com.Nvt.Celman.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Send a text message request.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <returns>SmsSendResponse</returns>
        SmsSendResponse SmsSend (SmsSendRequest smsSendRequest);

        /// <summary>
        /// Send a text message request.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <returns>ApiResponse of SmsSendResponse</returns>
        ApiResponse<SmsSendResponse> SmsSendWithHttpInfo (SmsSendRequest smsSendRequest);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Send a text message request.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of SmsSendResponse</returns>
        System.Threading.Tasks.Task<SmsSendResponse> SmsSendAsync (SmsSendRequest smsSendRequest, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Send a text message request.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (SmsSendResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SmsSendResponse>> SmsSendWithHttpInfoAsync (SmsSendRequest smsSendRequest, CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDefaultApi
    {
        private Com.Nvt.Celman.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(String basePath)
        {
            this.Configuration = new Com.Nvt.Celman.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Com.Nvt.Celman.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// </summary>
        /// <returns></returns>
        public DefaultApi()
        {
            this.Configuration = Com.Nvt.Celman.Client.Configuration.Default;

            ExceptionFactory = Com.Nvt.Celman.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(Com.Nvt.Celman.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Com.Nvt.Celman.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Com.Nvt.Celman.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Com.Nvt.Celman.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Com.Nvt.Celman.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Send a text message request. 
        /// </summary>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <returns>SmsSendResponse</returns>
        public SmsSendResponse SmsSend (SmsSendRequest smsSendRequest)
        {
             ApiResponse<SmsSendResponse> localVarResponse = SmsSendWithHttpInfo(smsSendRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Send a text message request. 
        /// </summary>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <returns>ApiResponse of SmsSendResponse</returns>
        public ApiResponse<SmsSendResponse> SmsSendWithHttpInfo (SmsSendRequest smsSendRequest)
        {
            // verify the required parameter 'smsSendRequest' is set
            if (smsSendRequest == null)
                throw new ApiException(400, "Missing required parameter 'smsSendRequest' when calling DefaultApi->SmsSend");

            var localVarPath = "/sms/send";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsSendRequest != null && smsSendRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(smsSendRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsSendRequest; // byte array
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsSend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SmsSendResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SmsSendResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SmsSendResponse)));
        }

        /// <summary>
        /// Send a text message request. 
        /// </summary>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of SmsSendResponse</returns>
        public async System.Threading.Tasks.Task<SmsSendResponse> SmsSendAsync (SmsSendRequest smsSendRequest, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<SmsSendResponse> localVarResponse = await SmsSendWithHttpInfoAsync(smsSendRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Send a text message request. 
        /// </summary>
        /// <exception cref="Com.Nvt.Celman.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSendRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (SmsSendResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SmsSendResponse>> SmsSendWithHttpInfoAsync (SmsSendRequest smsSendRequest, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'smsSendRequest' is set
            if (smsSendRequest == null)
                throw new ApiException(400, "Missing required parameter 'smsSendRequest' when calling DefaultApi->SmsSend");

            var localVarPath = "/sms/send";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsSendRequest != null && smsSendRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(smsSendRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsSendRequest; // byte array
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Auth-Token")))
            {
                localVarHeaderParams["X-Auth-Token"] = this.Configuration.GetApiKeyWithPrefix("X-Auth-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsSend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SmsSendResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SmsSendResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SmsSendResponse)));
        }

    }
}
